- docs/_config.yml
- docs/api/task.md
- docs/api/user.md
- docs/api/users-get-all-users.md
- docs/api/users-get-user-by-id.md
- docs/before-you-start-a-tutorial.md
- docs/index.md
- docs/tutorials.md
- docs/tutorials/add-a-new-task.md
- docs/tutorials/enroll-a-new-user.md
Updates the docs to incorporate a more styled template.
> Add basic elements of just-the-docs theme to the documentation

- docs/index.md
- docs/overview-levibeverly.md
This PR includes the improved overview topic needed for Assignment 6.1.
Note: I did not populate any links, given that this assignment only focuses on the overview topic itself.
> 6.1 PR - Drafted improved overview topic

- docs/api.md
- docs/community.md
- docs/index.md
- docs/overview_nikki_everett.md
- docs/quick-start.md
- docs/support.md
Adds a new overview page and placeholder supporting pages (quick-start, support, community).
> [Assignment 6.1] Add new overview page and supporting pages

- docs/index.md
- docs/overview-chood.md
Overview-chood contains a new Overview page for the To-do Service API documentation.
> Overview chood

- docs/index.md
- docs/overview-alicia.md
Rewrite for To-do API overview page.
> Assignment 6.1 Overview

- docs/index.md
- docs/overview_dmanis.md
changes:
* added new 'overview' topic: overview_dmanis.md
* added link to overview_dmanis.md in the existing index.md topic
> added new 'overview' topic: overview_dmanis.md

- docs/index.md
- docs/to-do-lp-jdn.md
Created a new LP for the To Do service and added a link to it from the primary To Do Overview page
> Created a new LP for the To Do service

- docs/api/users-get-user-by-id-CT.md
- docs/index.md
- docs/overview_CT.md
- docs/tutorials/create_first_task_CT.md
* Add files via upload
* Update create_first_task_CT.md
* Update overview_CT.md
> Assignments 6.1-6.3

- docs/index.md
- docs/overview_sy.md
This adds `overview_sy.md`, which is a new overview page for Assignment 6.1.
> Add a new and improved overview page for Assignment 6.1

- docs/index.md
- docs/overview_david.md
The following links are included in the new Overview page and are links for assignments 6.2 and 6.3:
6.2: `[Quickstart Guide](quickstart_guide_david.md)`
6.3: `[API Reference: Task by User ID](api/api_reference_task_by_user_id_david.md)`
> 6.1: New Overview page for To-Do Service API

- docs/index.md
- docs/tutorials.md
- docs/tutorials/delete-a-user-levibeverly.md
Replaces PR #14 which couldn't be merged due to merge commits.
Includes these additional changes to tidy up related topics:
* Update link text in index.md
* Update overview topic link text
* Add tutorials topic link to index.md
* Add link to new tutorial page
> Added new delete user tutorial from levigbeverly

- docs/api.md
- docs/api/tasks-get-all-tasks-nikki-everett.md
Adds a "Get all tasks" reference topic to the API section, similar to the existing "Get all users" topic.
> [Assignment 6.4] Add 'Get all tasks' reference topic

- docs/api.md
- docs/api/task-get-by-task-id.md
- docs/index.md
Adds a reference page for retrieving a task by task id
> Assignment 6.3 Reference

- docs/api.md
- docs/api/task.md
- docs/api/tasks-get-all-tasks-sophie.md
This adds `tasks-get-all-tasks.md`, which is a new API reference topic for Assignment 6.3.
> Add an API reference topic for Assignment 6.3.

- docs/index.md
- docs/quickstart_guide_david.md
Two links are for assignments 6.1 and 6.3:
6.1: `[Back to Landing Page](overview_david.md)`
6.3: `[API Reference: Task by User ID](api/api_reference_task_by_user_id_david.md)`
> 6.2: Created new first-use topic for To-Do Service API documentation

- docs/Quickstart_wuf.md
- docs/index.md
This branch was misnamed. It is really assignment 6.2 (Quickstart). I have hopefully successfully squashed the commits that deleted the Overview topic I started, and two mystery files that got created in the api folder. I modified to-do-db-source.json for my Quickstart, but could not see how to revert it. Crossing my fingers that I am at least getting my Quickstart in here. 
Deleted Extra files (api/-H and api/-d)
Don't know how these got here
Assignment6.2-WUF
Quickstart
Delete overview_WUF.md
> Squashed commit

- docs/index.md
- docs/tutorials/tutorial_sy.md
This adds `tutorial_sy.md`, which is a new tutorial page for Assignment 6.2.
> Add a new tutorial for Assignment 6.2.

- docs/index.md
- docs/tutorials/add-a-user_dmanis.md
added new 'create user' tutorial
Notes: 
* this pull request supersedes the existing request #25  
* Request #25 had some branching and merging issues so I cherry picked the changes to a new branch and new pull request 
changes:
* added new 'add-a-user_dmanis.md' tutorial file
* added link to the new tutorial from the existing docs index topic
* supporting assignment 6.2: 'Write a first use or a tutorial topic'
Applied edits from 6.2 code review
Changes:
* Expanded intro text
* Added an 'Overview' section
* Applied minor edit suggestions
* Added 'What's next?' section
* Fixed minor Markdown formatting warnings throughout
* Fixed anchor link to 'fetch user details'
> New 'create new user' tutorial

- docs/tutorials.md
- docs/tutorials/delete-a-task-nikki-everett.md
Adds a new tutorial on deleting tasks from the service using Postman.
> [Assignment 6.2] Add "Delete a task" tutorial

- docs/api.md
- docs/api/tasks-get-all-tasks_chood.md
- docs/tutorials/delete-a-task_chood.md
Added a Get all tasks reference page and updated spelling and wording on the Delete a task page.
> tasks-get-all-tasks_chood

- docs/index.md
- docs/tutorials/new-tutorial-jdn.md
Created a new tutorial for the To-Do Service.
> Create new-tutorial-jdn .md
